<?php

use \LiquidoBrl\PayInPhpSdk\Util\Brazil\PaymentMethod;
use \LiquidoBrl\PayInPhpSdk\Util\PayInStatus; ?>

<div class="liquido-container">
    <!-- <h1>Liquido Pagamentos</h1> -->

    <div>
        <img id="liquido-logo" src="<?php echo $this->getViewFileUrl("Liquido_PayIn::images/liquido-logo.png"); ?>" alt="Liquido Logo" >
    </div>
    
    <?php if (!$this->hasFailed()) : ?>
        <h3>Número do pedido: <?php echo $this->getOrderId() ?></h3>

        <?php if (
            $this->getPaymentMethodType() == PaymentMethod::BOLETO
            && $this->getTransferStatus() != PayInStatus::SETTLED
        ) : ?>
            <h2>Pague seu boleto pelo seu app de pagamentos ou Internet Banking</h2>
            <a target="_blank" href="<?php echo $this->getBoletoUrl() ?>">Baixar Boleto</a>
            <hr />
            <div id="boleto-digital-line-copy-paste">
                <fieldset class="fieldset">
                    <label for="boleto-digital-line">Se preferir, você pode pagá-lo copiando e colando o código abaixo:</label><br>
                    <input type="text" id="boleto-digital-line" name="boleto-digital-line" readonly value="<?php echo $this->getBoletoDigitalLine() ?>"><br>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button onclick="copyToClipboard('boleto-digital-line')" class="action primary" title="<?php echo __('Copiar código') ?>">
                            <span><?php echo __('Copiar código') ?></span>
                        </button>
                    </div>
                </div>
            </div>
        <?php elseif ($this->getTransferStatus() == PayInStatus::IN_PROGRESS) : ?>
            <h3><strong>Você já gerou um pagamento com <?php echo __($this->getPaymentMethodName()) ?></strong></h3>
        <?php elseif ($this->getTransferStatus() == PayInStatus::SETTLED) : ?>
            <h3><strong>Você já pagou com <?php echo __($this->getPaymentMethodName()) ?></strong></h3>
        <?php endif; ?>

    <?php else : ?>
        <a href="/checkout/liquidobrl/index">Alterar método de pagamento</a>
    <?php endif; ?>
</div>